spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/**

        - id: chat-service
          uri: ${CHAT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/chat/**

        - id: websocket-service
          uri: ${WEBSOCKET_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/ws/**

server:
  port: 8080
