spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: chat-service
          uri: http://chat-service:8082
          predicates:
            - Path=/chat/**

        - id: websocket-service
          uri: http://websocket-service:8083
          predicates:
            - Path=/ws/**

server:
  port: 8080